Remove helm v2 support
Signed-off-by: Brad Davidson <brad.davidson@rancher.com>

diff --git a/entry b/entry
--- a/entry
+++ b/entry
@@ -1,11 +1,7 @@
 #!/bin/bash
 
 helm_update() {
-	if [[ "${HELM}" == "helm_v3" ]]; then
-		LINE="$(${HELM} ls --all -f "^${NAME}\$" --namespace ${TARGET_NAMESPACE} --output json | jq -r "${JQ_CMD}" | tr '[:upper:]' '[:lower:]')"
-	else
-		LINE="$(${HELM} ls --all "^${NAME}\$" --output json | jq -r "${JQ_CMD}" | tr '[:upper:]' '[:lower:]')"
-	fi
+	LINE="$(${HELM} ls --all -f "^${NAME}\$" --namespace ${TARGET_NAMESPACE} --output json | jq -r "${JQ_CMD}" | tr '[:upper:]' '[:lower:]')"
 	IFS=, read -r INSTALLED_VERSION STATUS _ <<<${LINE}
 	VALUES=""
 
@@ -19,14 +15,8 @@ helm_update() {
 			echo "No ${HELM} chart installed; nothing to delete" >> ${TERM_LOG}
 			exit
 		fi
-		if [[ "${HELM}" == "helm_v3" ]]; then
-			echo "Uninstalling ${HELM} chart" >> ${TERM_LOG}
-			${HELM} uninstall ${NAME} --namespace ${TARGET_NAMESPACE} --wait || true
-		else
-			echo "Deleting and purging ${HELM} chart" >> ${TERM_LOG}
-			${HELM} delete ${NAME} || true
-			${HELM} "$@" --purge ${NAME}
-		fi
+		echo "Uninstalling ${HELM} chart" >> ${TERM_LOG}
+		${HELM} uninstall ${NAME} --namespace ${TARGET_NAMESPACE} --wait || true
 		exit
 	fi
 
@@ -37,8 +27,8 @@ helm_update() {
 		exit
 	fi
 
-	# If a previous helm_v3 operation was interrupted unexpectedly, set it to failed.
-	if [[ "${STATUS}" =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]] && [[ "${HELM}" == "helm_v3" ]]; then
+	# If a previous helm operation was interrupted unexpectedly, set it to failed.
+	if [[ "${STATUS}" =~ ^(pending-install|pending-upgrade|pending-rollback)$ ]]; then
 		echo Previous helm job was interrupted, updating status from ${STATUS} to failed
 		echo "Resetting ${HELM} release status from '${STATUS}' to 'failed'" >> ${TERM_LOG}
 		${HELM} set-status ${NAME} failed --namespace ${TARGET_NAMESPACE}
@@ -59,11 +49,7 @@ helm_update() {
 	# Upgrade only if the chart is already deployed
 	if [[ "${STATUS}" == "deployed" ]]; then
 		echo "Already installed ${NAME}"
-		if [[ "${HELM}" == "helm_v3" ]]; then
-			${HELM} mapkubeapis ${NAME} --namespace ${TARGET_NAMESPACE}
-		else
-			${HELM} mapkubeapis ${NAME} --v2
-		fi
+		${HELM} mapkubeapis ${NAME} --namespace ${TARGET_NAMESPACE}
 
 		echo "Upgrading ${HELM} chart" >> ${TERM_LOG}
 		echo "Upgrading ${NAME}"
@@ -75,13 +61,8 @@ helm_update() {
 	# The chart is in a bad state; try uninstalling it first
 	if [[ "${STATUS}" =~ ^(deleted|failed|null|unknown)$ ]]; then
 		if [[ "${FAILURE_POLICY:-reinstall}" == "reinstall" ]]; then
-			if [[ "${HELM}" == "helm_v3" ]]; then
-				echo "Uninstalling ${STATUS} ${HELM} chart" >> ${TERM_LOG}
-				${HELM} uninstall ${NAME} --namespace ${TARGET_NAMESPACE} --wait
-			else
-				echo "Purging ${STATUS} ${HELM} chart" >> ${TERM_LOG}
-				${HELM} "$@" --purge ${NAME}
-			fi
+			echo "Uninstalling ${STATUS} ${HELM} chart" >> ${TERM_LOG}
+			${HELM} uninstall ${NAME} --namespace ${TARGET_NAMESPACE} --wait
 			echo Deleted
 			# Try installing now that we've uninstalled
 			echo "Installing ${HELM} chart" >> ${TERM_LOG}
@@ -107,22 +88,13 @@ helm_repo_init() {
 		return
 	fi
 
-	if [[ "${HELM}" == "helm_v3" ]]; then
-		if [[ ${CHART} == stable/* ]]; then
-			${HELM} repo add ${CA_FILE_ARG} stable ${STABLE_REPO_URL}
-			${HELM} repo update
-		fi
-	else
-		${HELM} repo update --strict || ${HELM} repo remove stable
+	if [[ ${CHART} == stable/* ]]; then
+		${HELM} repo add ${CA_FILE_ARG} stable ${STABLE_REPO_URL}
+		${HELM} repo update
 	fi
 
 	if [[ -n "${REPO}" ]]; then
 		if [[ -f "${AUTH_DIR}/username" ]] && [[ -f "${AUTH_DIR}/password" ]]; then
-			if [[ "${HELM}" == "helm_v2" ]]; then
-				echo "Repo authentication is not supported with v2 charts" >> ${TERM_LOG}
-				echo "Repo authentication is not supported with v2 charts"
-				exit 1
-			fi
 			if [[ "${AUTH_PASS_CREDENTIALS}" == "true" ]]; then
 				PASS_CREDENTIALS_ARG="--pass-credentials"
 			fi
@@ -158,7 +130,7 @@ export TERM_LOG=/dev/termination-log
 export SSL_CERT_FILE=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
 export SSL_CERT_DIR=/etc/ssl/certs
 export HELM_TLS_CA_CERT=${SSL_CERT_FILE}
-HELM="helm_v3"
+HELM="helm"
 NAME_ARG=""
 CA_FILE_ARG=""
 TIMEOUT_ARG=""
@@ -175,23 +147,10 @@ fi
 
 set +v -x
 
-if [[ "${BOOTSTRAP}" != "true" ]]; then
-	tiller --listen=127.0.0.1:44134 --storage=secret &
-	export HELM_HOST=127.0.0.1:44134
-
-	helm_v2 init --skip-refresh --client-only --stable-repo-url ${STABLE_REPO_URL}
-	V2_CHART_EXISTS=$(timeout -s KILL 30 helm_v2 ls --all "^${NAME}\$" --output json | jq -r '.Releases | length')
-fi
-
-if [[ "${V2_CHART_EXISTS}" == "1" ]] || [[ "${HELM_VERSION}" == "v2" ]]; then
-	if [[ "${BOOTSTRAP}" == "true" ]]; then
-		echo "Can't bootstrap ${HELM} chart" >> ${TERM_LOG}
-		echo "Error: bootstrap flag can't be set with helm version 2 charts, please remove the bootstrap flag and update the chart"
-		exit 1
-	fi
-	HELM="helm_v2"
-	NAME_ARG="--name"
-	JQ_CMD='"\(.Releases[0].AppVersion),\(.Releases[0].Status)"'
+if [[ "${HELM_VERSION}" == "v2" ]]; then
+	echo "Helm v2 is EOL effective 2020-11-13; upgrade your chart to helm v3" >> ${TERM_LOG}
+	echo "Helm v2 is EOL effective 2020-11-13; upgrade your chart to helm v3"
+	exit 1
 fi
 
 shopt -s nullglob
@@ -211,11 +170,7 @@ if [[ -f "/tmp/ca-file.pem" ]]; then
 fi
 
 if [[ -n "${TIMEOUT}" ]]; then
-	if [[ "${HELM}" == "helm_v3" ]]; then
-		TIMEOUT_ARG="--timeout ${TIMEOUT}"
-	else
-		echo "Warning: timeout flag can't be set with version 2 charts, using default timeout"
-	fi
+	TIMEOUT_ARG="--timeout ${TIMEOUT}"
 fi
 
 helm_content_decode
