exit with error if bootstrap flag is passed with helm v2

diff --git a/entry b/entry
--- a/entry
+++ b/entry
@@ -109,6 +109,10 @@ if [ "$BOOTSTRAP" != "true" ]; then
 fi
 
 if [ "$EXIST" == "1" ] || [ "$HELM_VERSION" == "v2" ]; then
+  if [ "$BOOTSTRSP" == "true" ]; then
+    echo "Error: bootstrap flag can't be set with helm version 2 charts, please remove the bootstrap flag and update the chart"
+    exit 1
+  fi
 	HELM="helm_v2"
 	NAME_ARG="--name"
 	JQ_CMD='"\(.Releases[0].AppVersion),\(.Releases[0].Status)"'
